version: "3.9"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - VERSION=docker
#       - PLEX_CLAIM= #optional
      - SYSCALL_MAX_ENABLED=1
    volumes:
      - ~/docker-persistence-storage/plex/config:/config
      - ~/Movies:/movies
    restart: unless-stopped
